[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/news"
  to = "/.netlify/functions/news"
  status = 200
  force = true

[[redirects]]
  from = "/news?id=:id"
  to = "https://criticsbreakingnews.co.uk/?p=:id"
  status = 301
  force = true
  conditions = { 
    UserAgent = "facebookexternalhit/.*|Twitterbot/.*" 
  }
