[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/demo/article"
  to = "https://aubtu.biz/"
  status = 301
  force = true
  