[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/functions/news"
  to = "https://criticsbreakingnews.co.uk"
  status = 301
  force = true
  query = { id = ":id" }