[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/news?id=:id"
  to = "https://aubtu.biz/:id"
  status = 301
  force = true
  query = { id = ":id" }
  conditions = { Referrer =~ "/.*\.facebook\.com\/.*/i" }